#!/usr/bin/env bash
# This Bash script transfers a file from our client to a server

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign params to variables

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Disable strict host key checking
scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# Successful transfer check
if [ $? -eq 0 ]
then
    echo "FILE TRANSFERED SUCCESSFULLY"
else
    echo "FILE TRANSFER FAILED"
fi
