#!/usr/bin/env bash
# Configure Nginx server to redirect to another page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

replacement_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/imansai permanent;"

sudo sed -i "s/server_name _;/$replacement_string/" etc/nginx/sites-enabled/default

sudo service nginx restart
