#!/usr/bin/env bash
# HAproxy installation and setup

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 371624-web-01 18.234.253.254:80 check
   server 371624-web-02 54.175.27.121:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
