#!/usr/bin/env bash
# This script displays numbers from 1 to 100

num=1
while [ $num -ne 101 ]
do
    if [ $((num % 15)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((num % 3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $((num % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
	echo $num
    fi
    ((num++))
done
